### ISSUE TITLE
Dwm1000 working status

### ISSUE THREAD

**Issue by nagendra092918** [wahajmurtaza/Indoor-Positioning-and-Navigation-using-Reinforcement-Learning#1]
Dwm1000 not giving distance

**Comment by wahajmurtaza** [comment]
Try using my exact codes and baud rates, also tell me what you are getting in anchors.
And also upload the circuit diagram that you are using.

Also you must delete your dwm1000 library and use the one I provided in the link.

**Comment by nagendra092918** [comment]
tq for ur reply i used exact code what ever u given and library also i deleted previous one i downloaded and add ur mentioned library and these are the result for u code if use same baud rate which u mentioned in code and this is my connection circuit. please help me if i did any wrong 
     thank you  
![Screenshot from 2019-09-11 10-31-03](https://user-images.githubusercontent.com/29352982/64669516-788dba00-d47f-11e9-83c5-9281cb473391.png)
![Screenshot from 2019-09-11 10-29-00](https://user-images.githubusercontent.com/29352982/64669522-7f1c3180-d47f-11e9-9c1c-e6f4e907916d.png)

**Comment by wahajmurtaza** [comment]
I have personally tested all the codes and there is no issue with them. I suggest that you first try the basic sender and basic receiver from example. See if they are communicating.
I got some issues when going through the designing and I will discuss it below:
1. I got really garbage values and my  arduino kept resarting  when I was trying it out on bread-board with loose connections. The DWM1000 also got over-heat . This got removed by doing it on PCB.
2. Channel 5 and Channel 1 didn't work for me. You should try all the channels and select what's best for you.
3. FTDI programmer are real mess. They work for some time and after some time they create problem in uploading code and also restart arduino.
4. My sensors frequently disconnects and I found that this was due to power issue. I used 9v battery to power the arduino pro mini.  Also the pro-mini should be 3v.
5. You must select the power registor as per your country allocation to increase the range and stability.

**Comment by wahajmurtaza** [comment]
I reviewed the code and found that tag was on channel_7, the anchors and the tags should be on same channel. I have changed the channels to channel 5, clone it again or just change the tag channel.
My oversight.
Let me know if this solves your problem

**Comment by nagendra092918** [comment]
tq for ur reply could please show me the what is output(screen short) and pro mini processor selection(5v,16mhz or 3v,8mhz). which one u selected while upload program. is it required all anchors should connect laptop .

tag:
still i am getting garbage value

anchor:
add and inactive
![Screenshot from 2019-09-11 18-22-12](https://user-images.githubusercontent.com/29352982/64698862-4d2bbf00-d4c1-11e9-9f73-fb0a4ff6a0de.png)
![Screenshot from 2019-09-11 18-23-17](https://user-images.githubusercontent.com/29352982/64698880-5583fa00-d4c1-11e9-959c-cfd1489f3fef.png)

**Comment by wahajmurtaza** [comment]
Arduino pro mini selection should based on hardware. Note that dwm1000 is a 3v sensor. You must use arduino 3v if not the module can go bad. You can make a check the voltage between Vcc and GND to see the voltage. Also see the processor number. This seems to me that your device is restarting. I have mentioned the possibilities of restarting above. Look into it and detect your problem. Select appropriate device and voltage.
I dont have my devices on me but after it connects it starts giving range without disconnecting. Try Channel 3 also.

**Comment by wahajmurtaza** [comment]
No anchors are not required to be connected to laptop. Just needs powering them up. But its good for debugging.

**Comment by nagendra092918** [comment]
dwm 1000 i given 3.3v from pro mini vcc and ground, i changed to channel 3 but still getting same. and i tested all reaming codes working fine.
![Screenshot from 2019-09-11 19-53-51](https://user-images.githubusercontent.com/29352982/64705685-f8427580-d4cd-11e9-9afc-8c527b36be9d.png)

**Comment by wahajmurtaza** [comment]
Does the anchor show the distance?
The 2 meter was set for avoiding error in python,
It means that your sensors are not communicating.

Just try dwm1000ranging anchor and tag and see if they show up distancr.
Also use serial print command  in setup to check if the device resets.

**Comment by nagendra092918** [comment]
anchor and tag code working fine given distance
![Screenshot from 2019-09-11 20-45-09](https://user-images.githubusercontent.com/29352982/64710260-4018cb00-d4d5-11e9-8a93-bdf01b6d639c.png)

**Comment by nagendra092918** [comment]
both anchor and tag getting distance
![Screenshot from 2019-09-11 20-48-06](https://user-images.githubusercontent.com/29352982/64710422-8e2dce80-d4d5-11e9-9526-4f7e28b1dce2.png)

**Comment by nagendra092918** [comment]
when i connect two anchors by changing address the distance of one anchor is negative.why negative values are getting,what is the problem .please help
![Screenshot from 2019-09-11 21-00-45](https://user-images.githubusercontent.com/29352982/64711598-78210d80-d4d7-11e9-9dfb-c6dd27c38a06.png)
 value

**Comment by wahajmurtaza** [comment]
Use the same tag code,  but anchors from mine,  also test different
channels but change both of tag and anchor,

I must also tell you this as per mine experiment and many others that the
dwm1000 works best with atleast 2 meter distamce between tag and anchor.

For lower distance you need to calibrate antenna delay,  see the user
manual of dw1000.

**Comment by wahajmurtaza** [comment]
If you are getting accurate results with only negative value and some time
garbage in between,  just take absolute values of the ranges and filter out the value
which will not be in your parameters.

**Comment by nagendra092918** [comment]
could u please explain how u fixed the address as 11,12,13. actually what is this values 11,12,13 why
![Screenshot from 2019-09-11 21-48-36](https://user-images.githubusercontent.com/29352982/64715530-4790a200-d4de-11e9-9982-15eb5f02b228.png)
 ur comparing with this value

**Comment by wahajmurtaza** [comment]
When you use false in start as anchor the firsr four letters if address are
short address,  which are in hex format,

ie 11 for B,  12 for C and 13 for D
0B:00 means 11

**Comment by nagendra092918** [comment]
tq bro how increase the accuracy of distance and sometimes getting negative values and that is not correct distance.how to aviode negative value, now i want to do triangulation with same tag. is there any difficult
![Screenshot from 2019-09-12 10-27-17](https://user-images.githubusercontent.com/29352982/64755529-d803cc80-d548-11e9-893f-6aeef0aacf0c.png)
 to on tag triangulation

**Comment by wahajmurtaza** [comment]
The rest us easy mathematics, You can easiky manage.
Take absolute value of current distance every time.  This will correct  error for
sensor C

**Comment by nagendra092918** [comment]
u said power register for stable distance how to set that, what is "Take mod of current distance every time" i did not  get .please tell me

**Comment by wahajmurtaza** [comment]
Read user manual of dw1000, you will find all answers there. Also calibrate antenna delay. Consult data sheet and user manual.

**Comment by wahajmurtaza** [comment]
Just take absolute value of current_distance, this will solve your problem.

**Comment by nagendra092918** [comment]
ok tq somuch for u help if any problem i will ask please help

**Comment by nagendra092918** [comment]
finding position of tag using trilateration . i got the x value negitive value . i donot where i did mistake everything i written fine please check once my code is there any change or mistakes are there. please help me bro

[pos_ang.zip](https://github.com/wahajmurtaza/Indoor-Positioning-and-Navigation-using-Reinforcement-Learning/files/3609862/pos_ang.zip)

**Comment by wahajmurtaza** [comment]
the code seems fine, try plotting the coordinates and drawing the circles of radius, you will know what you are doing wrong.

**Comment by nagendra092918** [comment]
tq for ur reply my aim is to form the trilateration for finding position of tag. after geting tag position i will give one  position in linear graph based on position the rover should move to that position for this  required angle. so, my question is how to find the angle 0 to 359 degrees format and it should match with our magnetic compass . is it possible to find angle like this if u have any idea please help me in this. i tried alot but i did not get exactly

**Comment by wahajmurtaza** [comment]
Sorry for late reply, Did you solve your problem?

**Comment by nagendra092918** [comment]
tq for reply most probably solved but sometimes garbage values are getting

**Comment by wahajmurtaza** [comment]
Have you tried increasing the power? or changing data modes?

**Comment by nagendra092918** [comment]
no i will try and modes means

**Comment by ghost** [comment]
> tq for ur reply i used exact code what ever u given and library also i deleted previous one i downloaded and add ur mentioned library and these are the result for u code if use same baud rate which u mentioned in code and this is my connection circuit. please help me if i did any wrong
> thank you
> ![Screenshot from 2019-09-11 10-31-03](https://user-images.githubusercontent.com/29352982/64669516-788dba00-d47f-11e9-83c5-9281cb473391.png)
> ![Screenshot from 2019-09-11 10-29-00](https://user-images.githubusercontent.com/29352982/64669522-7f1c3180-d47f-11e9-9c1c-e6f4e907916d.png)

Hi Bro, How can you connect the arduino pro mini to PC? I don't see you the connection from your graph. Thanks.

**Comment by wahajmurtaza** [comment]
There is no need to connect pro mini to connect anchors to pc unless you
want data from it. The tag can provide all information.

For programming purpose I use ftdi programmer and to send data same
programmer can be used or usb/ttl can also be used.
