### ISSUE TITLE
Cannot use Library name.

### ISSUE THREAD

**Issue by ghost** [wahajmurtaza/Indoor-Positioning-and-Navigation-using-Reinforcement-Learning#4]

**Comment by ghost** [comment]
Hi Friend,

Problem:
no matching function for call to 'DW1000RangingClass::startAsAnchor(const char [24], const byte [3], const byte&, bool)'
![image](https://user-images.githubusercontent.com/57190671/74361726-577b1d80-4dbf-11ea-80b4-61d28aaecc96.png)

Please help me to see what is wrong with this?

**Comment by wahajmurtaza** [comment]
You should delete dw1000 library from arduino directory, then download mine in the libraries. This will solve the problem

**Comment by ghost** [comment]
Thanks for reply. I wanted to add your library. but it shows like this.
![image](https://user-images.githubusercontent.com/57190671/74365035-34536c80-4dc5-11ea-8b60-e4da6ef2ec88.png)

**Comment by wahajmurtaza** [comment]
You must be doing something wrong, just delete all the libraries of dw1000,

Then fresh clone my repository in libraries folder.

**Comment by ghost** [comment]
I delete everything and I install the Arduino again. but the DW1000 is still in the library. I don't know why.
![image](https://user-images.githubusercontent.com/57190671/74531500-b8703600-4f24-11ea-8cf2-81f69712ae35.png)
Did you meet this problem before? Thanks.

**Comment by ghost** [comment]
HI Friend,

I already clear everything. But I still can not including your library. is it because I install the Arduino 1.8.11?
![image](https://user-images.githubusercontent.com/57190671/74536147-6385ed00-4f2f-11ea-8613-23050d9bfdfe.png)
Thanks for help.

**Comment by wahajmurtaza** [comment]
Thats because you didnt delete the arduino folder for storing your projects and libraries.\
uninstall arduino and  delete \user\arduino folder. then do it again.\\
I am closing the issue as this is not related to library. See arduino forum for this.
